# Service PostgreSQL pour tous les magasins
services:
  ms-postgres-db:
    container_name: ms-postgres-db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - manage-shop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
